// Ace of Arenas. (invi1998 All Rights Reserved)

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"


namespace ArenasGameplayTags
{
	// InputTag
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_None);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_BasicAttack);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability1);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability2);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability3);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability4);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability5);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability6);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Confirm);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Cancel);
	
	// Gameplay Ability Tags
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack_Pressed);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack_Released);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Uppercut);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Passive_Launch_Activated);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_GroundBlast);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Shoot);

	/***** Event Tags *****/
	// Event-Combo
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Combo_Change_1);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Combo_Change_2);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Combo_Change_3);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Combo_Change_4);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Combo_Change_End);
	// Event-Uppercut
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Uppercut_Launch);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Uppercut_FinalBlow);
	// Event-Shoot
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Shoot_hand_L);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Shoot_hand_R);
	

	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Combo_Damage);

	// SetByCaller
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseDamage);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_ComboIndex);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Reward_Exp);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Reward_Gold);

	// Status
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dead);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Stun);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Aiming);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Health_Full);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Health_Empty);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Mana_Full);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Mana_Empty);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Damaged);

	// Cooldown
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ability_Uppercut);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ability_GroundBlast);
	// Cooldown for Item Active Ability
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Item_ArcaneBoots);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Item_BlackKingBar);

	// Role Type
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RoleType_Hero);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RoleType_Minion);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RoleType_Tower);
	
}
