// Ace of Arenas. (invi1998 All Rights Reserved)

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"


namespace ArenasGameplayTags
{
	// InputTag
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_None);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_BasicAttack);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability1);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability2);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability3);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability4);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability5);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability6);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Confirm);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Cancel);
	
	// Gameplay Ability Tags
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_BasicAttack);

	// Event
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Combo_Change_Combo02);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Combo_Change_Combo03);
	ARENAS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Combo_Change_Combo04);
	
}
